// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "2cf085e5-be1b-4bfe-890d-390bfd40ad48");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1568876645);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1568876765);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1568876165);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1568876405);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1568876285);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1568876525);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1568877005);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1568876885);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 84567);
user_pref("browser.cache.disk.capacity", 788480);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1568129989);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 86);
user_pref("browser.newtabpage.activity-stream.impressionId", "{015e9845-92ee-4f06-ac15-428f805eef28}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1568877978732");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1568879788732");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1568876136120");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1568879736120");
user_pref("browser.search.region", "FR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190828152820");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1568876135");
user_pref("browser.slowStartup.averageTime", 2593);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190828152820");
user_pref("browser.startup.homepage_override.mstone", "69.0");
user_pref("browser.startup.lastColdStartupCheck", 1568876135);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1568129992846");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "69.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "3e9f1a269c084eec9acafecd57f3b9c8");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Wed, 18 Sep 2019 14:19:52 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1568876645);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20190828152820");
user_pref("extensions.lastAppVersion", "69.0");
user_pref("extensions.lastPlatformVersion", "69.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"e53cd555-6224-40e6-bf93-d5cd020c439b\",\"fxmonitor@mozilla.org\":\"49864f4c-e52c-4f7c-8e89-4d3e0bf272d0\",\"screenshots@mozilla.org\":\"b61ff82f-ced3-49bc-9ead-9f82457e2a27\",\"webcompat-reporter@mozilla.org\":\"9a8218ae-6753-4c0c-be95-f9412d29350e\",\"webcompat@mozilla.org\":\"8ca62b11-d058-4b0e-b0cd-844439f85253\",\"default-theme@mozilla.org\":\"6a8b3cc5-0f49-41dd-9e83-66f22d72f6ff\",\"google@search.mozilla.org\":\"c1c6e594-a186-4e52-badc-8544d23187fd\",\"amazondotcom@search.mozilla.org\":\"44762d1e-5fbc-4488-bb7f-56245f414a1b\",\"bing@search.mozilla.org\":\"5e0b6d8a-9dd0-42f8-8f87-a71c62ff57a4\",\"ddg@search.mozilla.org\":\"c202e432-69f3-4150-b030-716cb8bb9c7d\",\"ebay@search.mozilla.org\":\"c52d0553-25de-4984-b42e-0c14f7b0735b\",\"twitter@search.mozilla.org\":\"ebc8278c-4d7c-4312-85f1-6ccb20c279e4\",\"wikipedia@search.mozilla.org\":\"32ab72f7-ae74-4636-82b9-7cf069152f8b\",\"amazon@search.mozilla.org\":\"fde966f4-149a-4f99-b60a-117a531406fc\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1568876554);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1568876395);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20190828152820");
user_pref("media.gmp-manager.lastCheck", 1568876394);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("permissions.eventTelemetry.salt", "{4bc54cff-4b91-48a8-8781-76ae0ebe4d4a}");
user_pref("places.database.lastMaintenance", 1568876554);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "967f004b-dd76-4b37-9a38-0d41968ebdb3");
user_pref("security.sandbox.plugin.tempDirSuffix", "a4384352-df8e-4b60-91e5-f1ea0ba328ba");
user_pref("services.blocklist.pinning.checked", 1568876599);
user_pref("services.settings.clock_skew_seconds", -75);
user_pref("services.settings.last_etag", "\"1568816392824\"");
user_pref("services.settings.last_update_seconds", 1568876599);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1568876599);
user_pref("services.settings.main.cfr-fxa.last_check", 1568876599);
user_pref("services.settings.main.cfr.last_check", 1568876599);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1568876599);
user_pref("services.settings.main.hijack-blocklists.last_check", 1568876599);
user_pref("services.settings.main.language-dictionaries.last_check", 1568876599);
user_pref("services.settings.main.normandy-recipes.last_check", 1568876599);
user_pref("services.settings.main.sites-classification.last_check", 1568876599);
user_pref("services.settings.main.tippytop.last_check", 1568876599);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1568876599);
user_pref("services.settings.security.onecrl.checked", 1568876599);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1568876554);
user_pref("toolkit.startup.last_success", 1568876133);
user_pref("toolkit.telemetry.cachedClientID", "0be166c7-e2f0-40a8-a887-aa4e00d42c8a");
user_pref("toolkit.telemetry.previousBuildID", "20190828152820");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
